name: consultant_product
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  resize: ^1.0.0
  global_configuration: ^2.0.0-nullsafety.1

  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  intl_phone_field: ^3.0.1
  pin_code_fields: ^7.3.0

  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  skeleton_loader: ^2.0.0+4

  # file_picker: ^4.6.1
  file_picker: ^5.2.9
  image_picker_gallery_camera: ^0.2.2
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  datetime_picker_formfield: ^2.0.1
  syncfusion_flutter_calendar: ^20.2.39

  mask_text_input_formatter: ^2.4.0
  animation_wrappers: ^3.0.0
  modal_bottom_sheet: ^2.1.2

  permission_handler: ^10.2.0
  syncfusion_flutter_charts: ^20.3.57

  rounded_expansion_tile: ^0.0.13
  progress_indicator: ^0.2.2
  pull_to_refresh: ^2.0.0

  maps_launcher: ^2.0.1

  photo_view: ^0.14.0
  flutter_inappwebview: ^5.4.4+3
  url_launcher: ^6.1.6

  geolocator: ^9.0.2
  geocoding: ^2.0.5
  app_settings: ^4.1.8
  uuid: ^3.0.7
  flutterwave_standard: ^1.0.6
  razorpay_flutter: ^1.3.4
  flutter_vibrate: ^1.3.0
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^5.0.6
  flutter_html: ^3.0.0-alpha.6
  html_editor_enhanced: ^2.5.0
  paytm_allinonesdk: ^1.2.0
  html: ^0.15.1
  dropdown_search: ^5.0.6
  search_choices: ^2.2.5
  multiselect: ^0.0.7


  #agora call video/audio
  agora_rtc_engine: ^5.2.0
  intl: ^0.17.0

  # pusher client for constlive chat event
  pusher_client: ^2.0.0

  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2

  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^9.0.2
  flutter_ringtone_player: ^3.1.0

  # device_info_plus: ^3.2.1
  device_info_plus: ^8.2.0
  file: ^6.1.4
  change_app_package_name: ^1.1.0
  rename: ^2.1.1
  upi_india: ^3.0.1

dependency_overrides:
   modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/images/
    - assets/Icons/


  fonts:
    - family: SarabunBold
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
    - family: SarabunExtraBold
      fonts:
        - asset: assets/fonts/Sarabun-ExtraBold.ttf
    - family: SarabunExtraLight
      fonts:
        - asset: assets/fonts/Sarabun-ExtraLight.ttf
    - family: SarabunLight
      fonts:
        - asset: assets/fonts/Sarabun-Light.ttf
    - family: SarabunMedium
      fonts:
        - asset: assets/fonts/Sarabun-Medium.ttf
    - family: SarabunRegular
      fonts:
        - asset: assets/fonts/Sarabun-Regular.ttf
    - family: SarabunSemiBold
      fonts:
        - asset: assets/fonts/Sarabun-SemiBold.ttf
    - family: SarabunThin
      fonts:
        - asset: assets/fonts/Sarabun-Thin.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
